[package]
name = "narrow"
version = "0.2.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2021"
# rust-version = "1.56.1" - nightly
description = "An implementation of Apache Arrow"
readme = "README.md"
repository = "https://github.com/mbrobbel/narrow"
documentation = "http://docs.rs/narrow/"
license = "Apache-2.0 OR MIT"
keywords = ["Arrow"]
categories = ["data-structures"]

[features]
default = ["nightly"]
nightly = ["extend_one", "simd"]

extend_one = []
simd = []

[dependencies]
# narrow-derive = { version = "0.1.0", path = "narrow-derive" }

[dev-dependencies]
arrow2 = { version = "0.10", features = ["simd"] }
bitvec = "1"
criterion = "0.3"
rand = "0.8"

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
lto = true
codegen-units = 1

[[bench]]
name = "narrow"
harness = false

[workspace]
members = [
  # "narrow-derive"
]
